baseURL = "http://fabiothiroki.github.io/"
languageCode = "en-us"
title = "Fabio Hiroki"  
theme = "pulp"
publishDir = ""

[params]
    author = "Fabio Hiroki"
    avatar = "avatar.jpg"
    description = """
        Hi, I'm a software developer who likes to build great teams 
        and meaningful applications.
    """

[[menu.main]]
    identifier = "stack-overflow"
    pre = "<i class='fab fa-stack-overflow fa-lg'></i>"
    url = "https://stackoverflow.com/users/980852/f%C3%A1bio-hiroki"
    weight = 5

[[menu.main]]
    identifier = "medium"
    pre = "<i class='fab fa-medium fa-lg'></i>"
    url = "https://medium.com/@fabiohiroki"
    weight = 4

[[menu.main]]
    identifier = "goodreads"
    pre = "<i class='fab fa-goodreads fa-lg'></i>"
    url = "https://www.goodreads.com/fabiothiroki"
    weight = 6

[[menu.main]]
    identifier = "github"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/fabiothiroki"
    weight = 2

[[menu.main]]
    identifier = "linkedin"
    pre = "<i class='fab fa-linkedin fa-lg'></i>"
    url = "https://www.linkedin.com/in/fabio-hiroki-b6739214/"
    weight = 1